# for module compiling
import os
Import('RTT_ROOT')

cwd = str(Dir('#'))
objs = []
list = os.listdir(cwd)

# Add CMSIS and NXP chip level drivers
objs += SConscript(cwd + "/../../libraries/SConscript")
# Add RT-Thread lowlevel drivers
objs += SConscript(cwd + "/../../drivers/SConscript")

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
