from building import *
Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]
if not src:
    if rtconfig.PLATFORM == 'armcc':
        LIBS    = ['nftl_rvds']
    else:
        LIBS    = ['nftl_gcc']
    LIBPATH = [cwd]
else:
    LIBS    = []
    LIBPATH = []

group   = DefineGroup('nftl', src, depend = ['RT_USING_NFTL', 'RT_USING_MTD_NAND', 'RT_USING_DFS', 'RT_USING_DFS_ELMFAT'], CPPPATH = CPPPATH, LIBS = LIBS, LIBPATH=LIBPATH)

Return('group')
