# RT-Thread building script for component

from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')

group = DefineGroup('RTGUI', src, depend = ['RTGUI_USING_CALI'])

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
