import os
import sys
import SCons.cpp
import rtconfig 

sconstruct = File('SConstruct')
fn = sconstruct.rfile()
name = fn.name
building_dir = os.path.dirname(fn.abspath)
program_dir  = r'..\bin'

if os.getenv('RTT_ROOT'):
    RTT_ROOT = os.getenv('RTT_ROOT')
else:
    # we use setting on rtconfig.py
    RTT_ROOT = rtconfig.RTT_ROOT

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *

Export('RTT_ROOT')

# add target option
AddOption('--app',
  dest='app',
  nargs=1, type='string',
  action='store',
  metavar='DIR',
  help='installation prefix')

# add target option
AddOption('--type',
  dest='type',
  nargs=1, type='string',
  action='store',
  metavar='DIR',
  help='installation prefix')

if GetOption('type') == 'ext':
    linkflags = rtconfig.LFLAGS + ' -e 0'
else:
    linkflags = rtconfig.LFLAGS + ' -e main'

env = Environment(tools = ['mingw'],
        AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
        CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
        CXX = rtconfig.CXX, AR = rtconfig.AR, ARFLAGS = '-rc',
        LINK = rtconfig.LINK, LINKFLAGS = linkflags,
        CPPPATH = [os.path.join(building_dir), 
                RTT_ROOT + '/include',
                RTT_ROOT + '/components/finsh',
                RTT_ROOT + '/components/dfs', 
                RTT_ROOT + '/components/dfs/include',
                RTT_ROOT + '/components/net/lwip-1.4.1/src', 
                RTT_ROOT + '/components/net/lwip-1.4.1/src/include', 
                RTT_ROOT + '/components/net/lwip-1.4.1/src/include/ipv4', 
                RTT_ROOT + '/components/net/lwip-1.4.1/src/arch/include', 
                building_dir + '/rtgui/include',
                ])
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)

PrepareModuleBuilding(env, RTT_ROOT)

app = GetOption('app')
if app:
    objs = SConscript(os.path.join(app, 'SConscript'))
    TARGET = os.path.join(app , app + '.' + rtconfig.TARGET_EXT)

    # build program 
    target = env.Program(TARGET, objs)
    env.Command("$TARGET", target, action = Copy(program_dir, TARGET))
